#
# IMPORTANT.  OS X support is so experimental that you have to specifically
# request to have it enabled, on a per-repository basis.  See
# http://docs.travis-ci.com/user/multi-os/#Manual-intervention-required
#
# This file will still work, without OS X enabled, it just won't run those
# tests.
#
language: python

os:
    - linux
    # - osx

dist: xenial
# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
# addons:
#     apt:
#         packages:
#             - graphviz
#             - texlive-latex-extra
#             - dvipng
python:
    - 3.5
    - 3.6
    - 3.7
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - MAIN_CMD='nikola'
        - NIKOLA_VERSION=7.8.15
    matrix:
        - SETUP_CMD='build --strict'

matrix:
    # Don't wait for allowed failures.
    fast_finish: true

    # OS X support is still experimental, so don't penalize failures.
    allow_failures:
        # - os: osx
        - os: linux
          python: 3.6
          env: NIKOLA_VERSION=8.0.3

    include:
        # Check for sphinx doc build warnings - we do this first because it
        # runs for a long time
        # - os: linux
        #   python: 3.6
        #   env: SETUP_CMD='build_sphinx --warning-is-error'

        # More recent version of Nikola
        - os: linux
          python: 3.6
          env: NIKOLA_VERSION=8.0.3

        # Experimental OS X test.
        # As of March 2017, Python builds on OS X are not available.
        # See https://docs.travis-ci.com/user/languages/python/
        # - os: osx
        #   python: 3.5
        #   env: SETUP_CMD='test'

        # PEP 8 compliance.
        # - os: linux
        #   python: 3.6
        #   env: MAIN_CMD='pycodestyle' SETUP_CMD='--count py/desitransfer'

# before_install:
#     - curl ipinfo.io
#     - python -c 'import setuptools; print(setuptools.__version__)'

install:
    # - if [[ $MAIN_CMD == 'pycodestyle' ]]; then pip install pycodestyle; fi
    # - if [[ $SETUP_CMD == build_sphinx* ]]; then pip install Sphinx; fi
    # - if [[ $MAIN_CMD == 'coverage' ]]; then pip install coverage coveralls; fi
    # - pip install -r requirements.txt
    - pip install -U pip
    - pip install nikola==${NIKOLA_VERSION}

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    # - if [[ $MAIN_CMD == 'coverage' ]]; then coveralls; fi
